CREATE TABLE M_BIKE(	
    BIKE_ID VARCHAR2(20 CHAR) NOT NULL, 
	NAME VARCHAR2(100 CHAR) NOT NULL, 
	COLOR VARCHAR2(100 CHAR), 
	MODEL VARCHAR2(100 CHAR), 
	YEAR VARCHAR2(10 CHAR), 
	PRODUCER_ID VARCHAR2(20 CHAR) NOT NULL,
	CREATE_TIME TIMESTAMP (6) DEFAULT SYSDATE  NOT NULL,
	UPDATE_TIME TIMESTAMP (6) DEFAULT SYSDATE,
	 PRIMARY KEY (BIKE_ID)
);
   
   
CREATE SEQUENCE  BIKE_SEQ MINVALUE 1 MAXVALUE 999999999999 
	INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION;