CREATE TABLE M_PRODUCER(	
    PRODUCER_ID VARCHAR2(20 CHAR) NOT NULL, 
	PRODUCER_NAME VARCHAR2(100 CHAR) NOT NULL,
	CREATE_TIME TIMESTAMP (6) DEFAULT SYSDATE  NOT NULL,
	UPDATE_TIME TIMESTAMP (6) DEFAULT SYSDATE,
	 PRIMARY KEY (PRODUCER_ID)
);
   
   
CREATE SEQUENCE  PRODUCER_SEQ MINVALUE 1 MAXVALUE 999999999999 
	INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION;