CREATE TABLE M_USER(	
    USER_ID VARCHAR2(20 CHAR) NOT NULL, 
	FULL_NAME VARCHAR2(100 CHAR) NOT NULL,
	CREATE_TIME TIMESTAMP (6) DEFAULT SYSDATE  NOT NULL,
	UPDATE_TIME TIMESTAMP (6) DEFAULT SYSDATE,
	 PRIMARY KEY (USER_ID)
);
   
   
CREATE SEQUENCE  USER_SEQ MINVALUE 1 MAXVALUE 999999999999 
	INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION;