CREATE TABLE M_USER_BIKE(	
    USER_ID VARCHAR2(20 CHAR) NOT NULL, 
	BIKE_ID VARCHAR2(20 CHAR) NOT NULL,
	CREATE_TIME TIMESTAMP (6) DEFAULT SYSDATE  NOT NULL,
	UPDATE_TIME TIMESTAMP (6) DEFAULT SYSDATE,
	 PRIMARY KEY (USER_ID, BIKE_ID)
);
